# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-04 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='absent',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='records',
            name='image',
            field=models.ImageField(default='static/img/default.jpg', upload_to='static/img'),
        ),
        migrations.AddField(
            model_name='records',
            name='present',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='records',
            name='total',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
