# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_auto_20180405_0323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='absent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='present',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='records',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
